#insert into
ymrc_country(id,language_id,code,allowed,phone_key,priority,name) values
(100, 1, '', 0, '', 99, "Afghanistan"); #
<option value="([a-zA-Z0-9]*)">(\S*)</option>

** ARABIC

<option value="et">أثيوبيا</option>
<option value="az">أذربيجان</option>
<option value="er">أرتيريا</option>
<option value="am">أرمينيا</option>
<option value="aw">أروبا</option>
<option value="au">أستراليا</option>
<option value="af">أفغانستان</option>
<option value="al">ألبانيا</option>
<option value="de">ألمانيا</option>
<option value="aq">أنتاركتيكا</option>
<option value="ag">أنتيغوا وبربودا</option>
<option value="ai">أنجويلا</option>
<option value="ad">أندورا</option>
<option value="ao">أنغولا</option>
<option value="uy">أوروغواي</option>
<option value="uz">أوزباكستان</option>
<option value="ug">أوغندا</option>
<option value="ua">أوكرانيا</option>
<option value="ie">أيرلندا</option>
<option value="is">أيسلندا</option>
<option value="es">إسبانيا</option>
<option value="ee">إستونيا</option>
<option value="il">إسرائيل</option>
<option value="io">إقليم المحيط الهندي البريطاني</option>
<option value="id">إندونيسيا</option>
<option value="ir">إيران</option>
<option value="it">إيطاليا</option>
<option value="ps">الأراضي الفلسطينية</option>
<option value="ar">الأرجنتين</option>
<option value="jo">الأردن</option>
<option value="ec">الإكوادور</option>
<option value="ae">الإمارات العربية المتحدة</option>
<option value="bh">البحرين</option>
<option value="br">البرازيل</option>
<option value="pt">البرتغال</option>
<option value="ba">البوسنة والهرسك</option>
<option value="me">الجبل الأسود</option>
<option value="dz">الجزائر</option>
<option value="um">الجزر النائية الصغرى للولايات المتحدة</option>
<option value="dk">الدنمارك</option>
<option value="sv">السلفادور</option>
<option value="sn">السنغال</option>
<option value="sd">السودان</option>
<option value="se">السويد</option>
<option value="eh">الصحراء الغربية</option>
<option value="so">الصومال</option>
<option value="cn">الصين</option>
<option value="iq">العراق</option>
<option value="ga">الغابون</option>
<option value="ph">الفلبين</option>
<option value="cm">الكاميرون</option>
<option value="cg">الكونغو</option>
<option value="kw">الكويت</option>
<option value="mv">المالديف</option>
<option value="hu">المجر (هنغاريا)</option>
<option value="ma">المغرب</option>
<option value="tf">المقاطعات الجنوبية الفرنسية</option>
<option value="mx">المكسيك</option>
<option value="sa">المملكة العربية السعودية</option>
<option value="uk">المملكة المتحدة</option>
<option value="xe">المنطقة المحايدة بين العراق والسعودية</option>
<option value="no">النرويج</option>
<option value="at">النمسا</option>
<option value="ne">النيجر</option>
<option value="in">الهند</option>
<option value="us">الولايات المتحدة</option>
<option value="jp">اليابان</option>
<option value="ye">اليمن</option>
<option value="gr">اليونان</option>
<option value="pg">بابوا غينيا الجديدة</option>
<option value="py">باراغواي</option>
<option value="pk">باكستان</option>
<option value="pw">بالاو</option>
<option value="bw">بتسوانا</option>
<option value="bb">بربادوس</option>
<option value="bm">برمودا</option>
<option value="bn">بروناي</option>
<option value="be">بلجيكا</option>
<option value="bg">بلغاريا</option>
<option value="bz">بليز</option>
<option value="bd">بنغلاديش</option>
<option value="pa">بنما</option>
<option value="bt">بوتان</option>
<option value="pr">بورتوريكو</option>
<option value="bf">بوركينا فاسو</option>
<option value="bi">بوروندي</option>
<option value="pl">بولندا</option>
<option value="bo">بوليفيا</option>
<option value="pf">بولينيزيا الفرنسية</option>
<option value="pe">بيرو</option>
<option value="bj">بينين</option>
<option value="th">تايلاند</option>
<option value="tw">تايوان</option>
<option value="tm">تركمانستان</option>
<option value="tr">تركيا</option>
<option value="tt">ترينيداد وتوباغو</option>
<option value="td">تشاد</option>
<option value="cl">تشيلي</option>
<option value="tz">تنزانيا</option>
<option value="tg">توغو</option>
<option value="tv">توفالو</option>
<option value="tk">توكيلو</option>
<option value="tn">تونس</option>
<option value="to">تونغا</option>
<option value="tl">تيمور الشرقية</option>
<option value="jm">جامايكا</option>
<option value="gi">جبل طارق</option>
<option value="gl">جرينلاند</option>
<option value="ax">جزر آلاند</option>
<option value="an">جزر الأنتيل الهولندية</option>
<option value="bs">جزر البهاما</option>
<option value="km">جزر القمر</option>
<option value="ki">جزر الكيريباتي</option>
<option value="pn">جزر بيتكيرن</option>
<option value="tc">جزر تركس وكايكوس</option>
<option value="pi">جزر سبراتلي</option>
<option value="sb">جزر سليمان</option>
<option value="fo">جزر فارو</option>
<option value="fk">جزر فوكلاند</option>
<option value="vi">جزر فيرجين الأمريكية</option>
<option value="vg">جزر فيرجين البريطانية</option>
<option value="ky">جزر كايمان</option>
<option value="ck">جزر كوك</option>
<option value="cc">جزر كوكوس (كيلنج)</option>
<option value="mh">جزر مارشال</option>
<option value="mp">جزر ماريانا الشمالية</option>
<option value="cv">جزيرة الرأس الأخضر</option>
<option value="cx">جزيرة الكريسماس</option>
<option value="bv">جزيرة بوفيه</option>
<option value="nf">جزيرة نورفولك</option>
<option value="hm">جزيرة هيرد وجزر ماكدونالد</option>
<option value="cf">جمهورية أفريقيا الوسطى</option>
<option value="cz">جمهورية التشيك</option>
<option value="do">جمهورية الدومنيكان</option>
<option value="cd">جمهورية الكونغو الديمقراطية</option>
<option value="za">جنوب أفريقيا</option>
<option value="gs">جورجيا الجنوبية وجزر ساندويتش الجنوبية</option>
<option value="ge">جورجيا</option>
<option value="dj">جيبوتي</option>
<option value="dm">دومينيكا</option>
<option value="rw">رواندا</option>
<option value="by">روسيا البيضاء (بيلاروسيا)</option>
<option value="ru">روسيا</option>
<option value="ro">رومانيا</option>
<option value="re">ريونيون</option>
<option value="zm">زامبيا</option>
<option value="zw">زيمبابوي</option>
<option value="ci">ساحل العاج</option>
<option value="as">ساموا الأمريكية</option>
<option value="ws">ساموا</option>
<option value="sm">سان مارينو</option>
<option value="pm">سانت بيير وميكويلون</option>
<option value="vc">سانت فينسنت وجزر غرينادين</option>
<option value="kn">سانت كيتس ونيفس</option>
<option value="lc">سانت لوسيا</option>
<option value="sh">سانت هيلينا وتوابعها</option>
<option value="st">ساو تومي وبرنسيب</option>
<option value="lk">سريلانكا</option>
<option value="sj">سفالبارد وجان ماين</option>
<option value="sk">سلوفاكيا</option>
<option value="si">سلوفينيا</option>
<option value="sg">سنغافورة</option>
<option value="sz">سوازيلند</option>
<option value="sy">سوريا</option>
<option value="sr">سورينام</option>
<option value="ch">سويسرا</option>
<option value="sl">سيراليون</option>
<option value="sc">سيشيل</option>
<option value="rs">صربيا</option>
<option value="tj">طاجكستان</option>
<option value="om">عمان</option>
<option value="gm">غامبيا</option>
<option value="gh">غانا</option>
<option value="gd">غرينادا</option>
<option value="gt">غواتيمالا</option>
<option value="gp">غوادلوب</option>
<option value="gu">غوام</option>
<option value="gf">غويانا الفرنسية</option>
<option value="gy">غويانا</option>
<option value="gq">غينيا الاستوائية</option>
<option value="gn">غينيا</option>
<option value="gw">غينيا-بيساو</option>
<option value="vu">فانواتو</option>
<option value="fr">فرنسا</option>
<option value="ve">فنزويلا</option>
<option value="fi">فنلندا</option>
<option value="vn">فيتنام</option>
<option value="fj">فيجي</option>
<option value="cy">قبرص</option>
<option value="qa">قطر</option>
<option value="kg">قيرغيزستان</option>
<option value="kz">كازاخستان</option>
<option value="nc">كاليدونيا الجديدة</option>
<option value="kh">كامبوديا</option>
<option value="hr">كرواتيا</option>
<option value="ca">كندا</option>
<option value="cu">كوبا</option>
<option value="kr">كوريا الجنوبية</option>
<option value="kp">كوريا الشمالية</option>
<option value="cr">كوستاريكا</option>
<option value="co">كولومبيا</option>
<option value="ke">كينيا</option>
<option value="lv">لاتفيا</option>
<option value="la">لاوس</option>
<option value="lb">لبنان</option>
<option value="lu">لوكسمبورغ</option>
<option value="lr">ليبريا</option>
<option value="ly">ليبيا</option>
<option value="lt">ليتوانيا</option>
<option value="li">ليختنشتاين</option>
<option value="ls">ليسوتو</option>
<option value="mq">مارتينيك</option>
<option value="mo">ماكاو</option>
<option value="mt">مالطا</option>
<option value="ml">مالي</option>
<option value="my">ماليزيا</option>
<option value="yt">مايوت</option>
<option value="mg">مدغشقر</option>
<option value="va">مدينة الفاتيكان</option>
<option value="eg">مصر</option>
<option value="mk">مقدونيا</option>
<option value="mw">ملاوي</option>
<option value="xx">منطقة متنازع عليها</option>
<option value="mn">منغوليا</option>
<option value="mr">موريتانيا</option>
<option value="mu">موريشيوس</option>
<option value="mz">موزمبيق</option>
<option value="md">مولدوفا</option>
<option value="mc">موناكو</option>
<option value="ms">مونتسرات</option>
<option value="mm">ميانمار</option>
<option value="na">ناميبيا</option>
<option value="nr">ناورو</option>
<option value="np">نيبال</option>
<option value="ng">نيجيريا</option>
<option value="ni">نيكاراغوا</option>
<option value="nz">نيوزيلندا</option>
<option value="nu">نيوي</option>
<option value="ht">هايتي</option>
<option value="hn">هندوراس</option>
<option value="nl">هولندا</option>
<option value="hk">هونغ كونغ</option>
<option value="wf">والس وفوتونا</option>
<option value="fm">ولايات ميكرونيسيا المتحدة</option>

** ENGLISH

<option value="af">Afghanistan</option>
<option value="ax">Aland Islands</option>
<option value="al">Albania</option>
<option value="dz">Algeria</option>
<option value="as">American Samoa</option>
<option value="ad">Andorra</option>
<option value="ao">Angola</option>
<option value="ai">Anguilla</option>
<option value="aq">Antarctica</option>
<option value="ag">Antigua and Barbuda</option>
<option value="ar">Argentina</option>
<option value="am">Armenia</option>
<option value="aw">Aruba</option>
<option value="au">Australia</option>
<option value="at">Austria</option>
<option value="az">Azerbaijan</option>
<option value="bs">Bahamas</option>
<option value="bh">Bahrain</option>
<option value="bd">Bangladesh</option>
<option value="bb">Barbados</option>
<option value="by">Belarus</option>
<option value="be">Belgium</option>
<option value="bz">Belize</option>
<option value="bj">Benin</option>
<option value="bm">Bermuda</option>
<option value="bt">Bhutan</option>
<option value="bo">Bolivia</option>
<option value="ba">Bosnia and Herzegovina</option>
<option value="bw">Botswana</option>
<option value="bv">Bouvet Island</option>
<option value="br">Brazil</option>
<option value="io">British Indian Ocean Territory</option>
<option value="vg">British Virgin Islands</option>
<option value="bn">Brunei</option>
<option value="bg">Bulgaria</option>
<option value="bf">Burkina Faso</option>
<option value="bi">Burundi</option>
<option value="kh">Cambodia</option>
<option value="cm">Cameroon</option>
<option value="ca">Canada</option>
<option value="cv">Cape Verde</option>
<option value="ky">Cayman Islands</option>
<option value="cf">Central African Republic</option>
<option value="td">Chad</option>
<option value="cl">Chile</option>
<option value="cn">China</option>
<option value="cx">Christmas Island</option>
<option value="cc">Cocos (Keeling) Islands</option>
<option value="co">Colombia</option>
<option value="km">Comoros</option>
<option value="cg">Congo</option>
<option value="ck">Cook Islands</option>
<option value="cr">Costa Rica</option>
<option value="hr">Croatia</option>
<option value="cu">Cuba</option>
<option value="cy">Cyprus</option>
<option value="cz">Czech Republic</option>
<option value="cd">Democratic Republic of Congo</option>
<option value="dk">Denmark</option>
<option value="xx">Disputed Territory</option>
<option value="dj">Djibouti</option>
<option value="dm">Dominica</option>
<option value="do">Dominican Republic</option>
<option value="tl">East Timor</option>
<option value="ec">Ecuador</option>
<option value="eg">Egypt</option>
<option value="sv">El Salvador</option>
<option value="gq">Equatorial Guinea</option>
<option value="er">Eritrea</option>
<option value="ee">Estonia</option>
<option value="et">Ethiopia</option>
<option value="fk">Falkland Islands</option>
<option value="fo">Faroe Islands</option>
<option value="fm">Federated States of Micronesia</option>
<option value="fj">Fiji</option>
<option value="fi">Finland</option>
<option value="fr">France</option>
<option value="gf">French Guyana</option>
<option value="pf">French Polynesia</option>
<option value="tf">French Southern Territories</option>
<option value="ga">Gabon</option>
<option value="gm">Gambia</option>
<option value="ge">Georgia</option>
<option value="de">Germany</option>
<option value="gh">Ghana</option>
<option value="gi">Gibraltar</option>
<option value="gr">Greece</option>
<option value="gl">Greenland</option>
<option value="gd">Grenada</option>
<option value="gp">Guadeloupe</option>
<option value="gu">Guam</option>
<option value="gt">Guatemala</option>
<option value="gn">Guinea</option>
<option value="gw">Guinea-Bissau</option>
<option value="gy">Guyana</option>
<option value="ht">Haiti</option>
<option value="hm">Heard Island and Mcdonald Islands</option>
<option value="hn">Honduras</option>
<option value="hk">Hong Kong</option>
<option value="hu">Hungary</option>
<option value="is">Iceland</option>
<option value="in">India</option>
<option value="id">Indonesia</option>
<option value="ir">Iran</option>
<option value="iq">Iraq</option>
<option value="xe">Iraq-Saudi Arabia Neutral Zone</option>
<option value="ie">Ireland</option>
<option value="il">Israel</option>
<option value="it">Italy</option>
<option value="ci">Ivory Coast</option>
<option value="jm">Jamaica</option>
<option value="jp">Japan</option>
<option value="jo">Jordan</option>
<option value="kz">Kazakhstan</option>
<option value="ke">Kenya</option>
<option value="ki">Kiribati</option>
<option value="kw">Kuwait</option>
<option value="kg">Kyrgyzstan</option>
<option value="la">Laos</option>
<option value="lv">Latvia</option>
<option value="lb">Lebanon</option>
<option value="ls">Lesotho</option>
<option value="lr">Liberia</option>
<option value="ly">Libya</option>
<option value="li">Liechtenstein</option>
<option value="lt">Lithuania</option>
<option value="lu">Luxembourg</option>
<option value="mo">Macau</option>
<option value="mk">Macedonia</option>
<option value="mg">Madagascar</option>
<option value="mw">Malawi</option>
<option value="my">Malaysia</option>
<option value="mv">Maldives</option>
<option value="ml">Mali</option>
<option value="mt">Malta</option>
<option value="mh">Marshall Islands</option>
<option value="mq">Martinique</option>
<option value="mr">Mauritania</option>
<option value="mu">Mauritius</option>
<option value="yt">Mayotte</option>
<option value="mx">Mexico</option>
<option value="md">Moldova</option>
<option value="mc">Monaco</option>
<option value="mn">Mongolia</option>
<option value="me">Montenegro</option>
<option value="ms">Montserrat</option>
<option value="ma">Morocco</option>
<option value="mz">Mozambique</option>
<option value="mm">Myanmar</option>
<option value="na">Namibia</option>
<option value="nr">Nauru</option>
<option value="np">Nepal</option>
<option value="an">Netherlands Antilles</option>
<option value="nl">Netherlands</option>
<option value="nc">New Caledonia</option>
<option value="nz">New Zealand</option>
<option value="ni">Nicaragua</option>
<option value="ne">Niger</option>
<option value="ng">Nigeria</option>
<option value="nu">Niue</option>
<option value="nf">Norfolk Island</option>
<option value="kp">North Korea</option>
<option value="mp">Northern Mariana Islands</option>
<option value="no">Norway</option>
<option value="om">Oman</option>
<option value="pk">Pakistan</option>
<option value="pw">Palau</option>
<option value="ps">Palestinian Territories</option>
<option value="pa">Panama</option>
<option value="pg">Papua New Guinea</option>
<option value="py">Paraguay</option>
<option value="pe">Peru</option>
<option value="ph">Philippines</option>
<option value="pn">Pitcairn Islands</option>
<option value="pl">Poland</option>
<option value="pt">Portugal</option>
<option value="pr">Puerto Rico</option>
<option value="qa">Qatar</option>
<option value="re">Reunion</option>
<option value="ro">Romania</option>
<option value="ru">Russia</option>
<option value="rw">Rwanda</option>
<option value="sh">Saint Helena and Dependencies</option>
<option value="kn">Saint Kitts and Nevis</option>
<option value="lc">Saint Lucia</option>
<option value="pm">Saint Pierre and Miquelon</option>
<option value="vc">Saint Vincent and the Grenadines</option>
<option value="ws">Samoa</option>
<option value="sm">San Marino</option>
<option value="st">Sao Tome and Principe</option>
<option value="sa">Saudi Arabia</option>
<option value="sn">Senegal</option>
<option value="rs">Serbia</option>
<option value="sc">Seychelles</option>
<option value="sl">Sierra Leone</option>
<option value="sg">Singapore</option>
<option value="sk">Slovakia</option>
<option value="si">Slovenia</option>
<option value="sb">Solomon Islands</option>
<option value="so">Somalia</option>
<option value="za">South Africa</option>
<option value="gs">South Georgia and South Sandwich Islands</option>
<option value="kr">South Korea</option>
<option value="es">Spain</option>
<option value="pi">Spratly Islands</option>
<option value="lk">Sri Lanka</option>
<option value="sd">Sudan</option>
<option value="sr">Suriname</option>
<option value="sj">Svalbard and Jan Mayen</option>
<option value="sz">Swaziland</option>
<option value="se">Sweden</option>
<option value="ch">Switzerland</option>
<option value="sy">Syria</option>
<option value="tw">Taiwan</option>
<option value="tj">Tajikistan</option>
<option value="tz">Tanzania</option>
<option value="th">Thailand</option>
<option value="tg">Togo</option>
<option value="tk">Tokelau</option>
<option value="to">Tonga</option>
<option value="tt">Trinidad and Tobago</option>
<option value="tn">Tunisia</option>
<option value="tr">Turkey</option>
<option value="tm">Turkmenistan</option>
<option value="tc">Turks And Caicos Islands</option>
<option value="tv">Tuvalu</option>
<option value="vi">US Virgin Islands</option>
<option value="ug">Uganda</option>
<option value="ua">Ukraine</option>
<option value="ae">United Arab Emirates</option>
<option value="uk">United Kingdom</option>
<option value="um">United States Minor Outlying Islands</option>
<option value="us">United States</option>
<option value="uy">Uruguay</option>
<option value="uz">Uzbekistan</option>
<option value="vu">Vanuatu</option>
<option value="va">Vatican City</option>
<option value="ve">Venezuela</option>
<option value="vn">Vietnam</option>
<option value="wf">Wallis and Futuna</option>
<option value="eh">Western Sahara</option>
<option value="ye">Yemen</option>
<option value="zm">Zambia</option>
<option value="zw">Zimbabwe</option>
